---
  kind: pipeline
  type: docker
  name: default
  
  steps:
  - name: build
    image: klakegg/hugo:alpine
    commands:
    - apk add make
    - make public
  - name: deploy
    image: minio/mc
    environment:
      MINIO_ACCESS_KEY:
        from_secret: MINIO_ACCESS_KEY
      MINIO_SECRET_KEY:
        from_secret: MINIO_SECRET_KEY
    commands:
    - mc config host add website https://website.minio.rknt.de $${MINIO_ACCESS_KEY} $${MINIO_SECRET_KEY}
    - mc rb website/rknt.de
    - mc mb website/rknt.de
    - mc mirror --overwrite public website/rknt.de
